---

- name: Remote install python3
  shell: |
    {{ role_path }}/scripts/remote.install.python3.sh "{{ prop_ipaddress }}" "{{ prop_admin_username }}"
    if [[ "$?" != "0" ]]; then
      echo "Error executing script" 
    fi
  args:
    executable: /bin/bash
  register: expectresult
  changed_when: '"Changed" in expectresult.stdout'
  failed_when: '"Error" in expectresult.stdout'
  connection: local
  become: false
