---

# see https://www.linuxfromscratch.org/blfs/view/svn/postlfs/logon.html


- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ args_hostname_hostname }}"
  register: hostnameresult
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_hostname_ipaddress }}"
  become: true

- name: Conditionally reboot the machine with all defaults
  reboot:
  when: hostnameresult.changed
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_hostname_ipaddress }}"
  become: true
