---

- name: Add user config folder
  ansible.builtin.file:
    path: /home/{{ prop_admin_username }}/.config
    owner: "{{ prop_admin_username }}"
    group: "{{ prop_admin_groupname }}"
    mode: '0700'
    state: directory
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true
