---

- name: Add User
  shell: ../scripts/add.user.sh "{{ args_ipaddress }}" "{{ args_install_username }}" "{{ args_admin_username }}" "{{ args_admin_password }}"
  args:
    executable: /bin/bash
  register: expectresult
  changed_when: '"Changed" in expectresult.stdout'
  failed_when: '"Error" in expectresult.stdout'
  connection: local
  become: false
