---

- name: Add User
  shell: |
    {{ role_path }}/scripts/add.user.sh "{{ prop_ipaddress }}" "{{ prop_install_username }}" "{{ prop_admin_username }}" "{{ prop_admin_password }}"
    if [[ "$?" != "0" ]]; then
      echo "Error executing script" 
    fi
  args:
    executable: /bin/bash
  register: result
  changed_when: '"Changed" in result.stdout'
  failed_when: '("Error" in result.stdout) or ("Host key verification failed." in result.stdout)'
  vars:
    ansible_connection: local
  become: false

