---

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /etc/ssh/ssh_host_*
    state: absent
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: create host keys
  shell: |
    ls -las /etc/ssh
    echo "---------------"
    ssh-keygen -A
    if [[ "$?" != "0" ]]; then
      echo "Error executing script" 
    fi
    echo "---------------"
    ls -las /etc/ssh
  args:
    executable: /bin/bash
  register: result
  failed_when: '"Error" in result.stdout'
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Reboot the machine with all defaults
  reboot:
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true
