---

- ansible.builtin.include_role: # knownhost
    name: alex.preinstall.knownproxmoxhost

- ansible.builtin.include_role: # rebuild
    name: alex.proxmox.rebuild

- ansible.builtin.include_role: # waitstarted
    name: alex.preinstall.waitstarted

- ansible.builtin.include_role: # knownhost
    name: alex.preinstall.knownoshost

