---

- name: Ensure CA certificate folder exists
  file:
    path: "/usr/share/ca-certificates/{{ args_cert_basename }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_cert_ipaddress }}"
  become: true

- name: Copy CA certificates
  copy:
    src: "{{ args_cert_certificates_sources }}/{{ args_cert_certificates_ca }}.cer"
    dest: "/usr/share/ca-certificates/{{ args_cert_basename }}/{{ args_cert_certificates_ca }}.cer"
    owner: root
    group: root
    mode: 0755
  register: cacertresult1
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_cert_ipaddress }}"
  become: true

- name: Extend CA certficiate configuration
  shell: |
    if [ ! ` cat /etc/ca-certificates.conf | grep "{{ args_cert_basename }}/{{ args_cert_certificates_ca }}.cer" ` ]; then 
      echo "{{ args_cert_basename }}/{{ args_cert_certificates_ca }}.cer" >> /etc/ca-certificates.conf
      echo "changedtrue"
    else
      echo "changedfalse"
    fi
  args:
    executable: /bin/bash
  register: cacertresult2
  changed_when:
  - '"changedtrue" in cacertresult2.stdout'
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_cert_ipaddress }}"
  become: true

- name: Add CA Certificate
  shell: |
    update-ca-certificates
  args:
    executable: /bin/bash
  when: cacertresult1.changed or ("changedtrue" in cacertresult2.stdout)
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_cert_ipaddress }}"
  become: true

- name: Ensure certificate folder exists
  file:
    path: "/{{ args_cert_basename }}/certificates"
    state: directory
    owner: root
    group: root
    mode: 0755
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_cert_ipaddress }}"
  become: true

- name: Install a list of packages
  apt:
    deb: https://dl.step.sm/gh-release/cli/docs-ca-install/v0.23.1/step-cli_0.23.1_amd64.deb
    state: present
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_cert_ipaddress }}"
  become: true

- name: Check if key present
  shell: |
    ls "/{{ args_cert_basename }}/certificates/host.crt" 2> /dev/null
    if [ $? != "0" ] ; then
      echo absent
    fi
  args:
    executable: /bin/bash
  register: certresult
  changed_when: "false"
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_cert_ipaddress }}"
  become: true

- name: Create keys, certificate
  when: '"absent" in certresult.stdout'
  block:
    - name: create key
      shell: |
        step crypto keypair \
          "/{{ args_cert_basename }}/certificates/host.pub" \
          "/{{ args_cert_basename }}/certificates/host.key" \
          --kty=RSA \
          --size=2048 \
          --force --no-password --insecure
      args:
        executable: /bin/bash
      vars:
        ansible_connection: ssh
        ansible_host: "{{ args_cert_ipaddress }}"
      become: true

    - name: create certificate signing request
      shell: |
        step certificate create \
          --csr \
          --key "/{{ args_cert_basename }}/certificates/host.key" \
          "{{ args_cert_description }}" \
          "/{{ args_cert_basename }}/certificates/host.csr" \
          --san {{ args_cert_hostname }} \
          --san {{ args_cert_hostname }}.{{ args_cert_dns_local }} \
          --san localhost \
          --san {{ args_cert_ipaddress }} \
          --force
      args:
        executable: /bin/bash
      vars:
        ansible_connection: ssh
        ansible_host: "{{ args_cert_ipaddress }}"
      become: true

    - name: Copy CSR
      ansible.builtin.fetch:
        src: "/{{ args_cert_basename }}/certificates/host.csr"
        dest: "/tmp/{{ args_cert_hostname }}.csr"
        flat: yes
      vars:
        ansible_connection: ssh
        ansible_host: "{{ args_cert_ipaddress }}"
      become: true

    - name: Sign certificate
      shell: |
        step certificate sign \
        "/tmp/{{ args_cert_hostname }}.csr" \
        "{{ args_cert_certificates_sources }}/{{ args_cert_certificates_ca }}.cer" \
        "{{ args_cert_certificates_sources }}/{{ args_cert_certificates_ca }}.key" \
        --set CommonName={{ args_cert_hostname }} \
        --template "{{ args_cert_certificates_sources }}/{{ args_cert_certificates_server_template }}" \
        --set-file "{{ args_cert_certificates_sources }}/{{ args_cert_certificates_org_settings }}" \
        --not-after 8766h \
        --bundle > "/tmp/{{ args_cert_hostname }}.cer"
      args:
        executable: /bin/bash
      connection: local

    - name: Copy certificate
      copy:
        src: "/tmp/{{ args_cert_hostname }}.cer"
        dest: "/{{ args_cert_basename }}/certificates/host.cer"
        owner: root
        group: root
        mode: 0755
      vars:
        ansible_connection: ssh
        ansible_host: "{{ args_cert_ipaddress }}"
      become: true

- name: Ensure home data folder exists
  file:
    path: "/home/{{ args_cert_admin_username }}/.{{ args_cert_basename }}" 
    state: directory
    owner: "{{ args_cert_admin_username }}"
    group: "{{ args_cert_admin_groupname }}"
    mode: 0755
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_cert_ipaddress }}"
  become: true

###### TODO rethink if OK 
- name: Copy ssh certificates 2 
  copy:
    src: "~/.ssh"
    dest: "/home/{{ args_cert_admin_username }}"
    owner: "{{ args_cert_admin_username }}"
    group: "{{ args_cert_admin_groupname }}"
    mode: 0700
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_cert_ipaddress }}"
  become: true
