---

- ansible.builtin.include_role:
    name: alex.preinstall.knownproxmoxhost

- ansible.builtin.include_role:
    name: alex.proxmox.rebuild

- ansible.builtin.include_role:
    name: alex.preinstall.waitstarted

- ansible.builtin.include_role:
    name: alex.preinstall.knownoshost
