---

- name: Wait until {{ args_rebuild_ipaddress }} started 
  wait_for:
    port: 22
    host: '{{ args_rebuild_ipaddress }}'
    search_regex: OpenSSH
    delay: 1
    timeout: 300
  connection: local
  become: false

