---

- name: Wait until {{ prop_ipaddress }} started 
  wait_for:
    port: 22
    host: '{{ prop_ipaddress }}'
    search_regex: OpenSSH
    delay: 1
    timeout: 300
  connection: local
  become: false

