---

- name: Remote install python3
  shell: ../scripts/remote.install.python3.sh "{{ args_ipaddress }}"
  args:
    executable: /bin/bash
  register: expectresult
  changed_when: '"Changed" in expectresult.stdout'
  failed_when: '"Error" in expectresult.stdout'
  connection: local
