---

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/{{ item }}
    state: absent
  loop:
    - pve-enterprise.list

#- name: Copy apt sources list for Ubuntu 20.04
#  ansible.builtin.template:
#    src: "sources.list.ubuntu.2004.j2"
#    dest: "/etc/apt/sources.list"
#    owner: root
#    group: root
#    mode: 0755
#  when: ansible_facts.distribution == "Ubuntu" and ansible_facts.distribution_version == "20.04"

- name: Update cache
  apt:
    update_cache: yes
  changed_when: false
  failed_when: false

- name: Remove unused packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Upgrade all packages to the latest version
  apt:
    upgrade: full

