---

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/{{ item }}
    state: absent
  loop:
    - pve-enterprise.list
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_apt_ipaddress }}"
  become: true

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian/ bookworm-updates non-free-firmware main contrib non-free
    state: present
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_apt_ipaddress }}"
  become: true

- name: Update cache
  apt:
    update_cache: yes
  changed_when: false
  failed_when: false
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_apt_ipaddress }}"
  become: true

- name: Remove unused packages from the cache
  apt:
    autoclean: yes
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_apt_ipaddress }}"
  become: true

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_apt_ipaddress }}"
  become: true

- name: Upgrade all packages to the latest version
  apt:
    upgrade: full
  vars:
    ansible_connection: ssh
    ansible_host: "{{ args_apt_ipaddress }}"
  become: true

