---

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/{{ item }}
    state: absent
  loop:
    - pve-enterprise.list
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Update apt sources Debian 11
  ansible.builtin.template:
    src: sources.list.debian11.j2
    dest: "/etc/apt/sources.list"
    owner: "root"
    group: "root"
    mode: '0644'
  when: 'prop_os == "deb11"'
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Update apt sources Debian 12
  ansible.builtin.template:
    src: sources.list.debian12.j2
    dest: "/etc/apt/sources.list"
    owner: "root"
    group: "root"
    mode: '0644'
  when: 'prop_os == "deb12"'
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Update cache
  apt:
    update_cache: yes
  changed_when: false
  failed_when: false
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Remove unused packages from the cache
  apt:
    autoclean: yes
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Upgrade all packages to the latest version
  apt:
    upgrade: full
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

