---

- name: Update Known Hosts
  shell: "{{ role_path }}/scripts/knownhosts.sh '{{ role_path }}' '{{ ansible_host }}'"
  args:
    executable: /bin/bash
  register: expectresult
  changed_when: '"Changed" in expectresult.stdout'
  failed_when: '"Error" in expectresult.stdout'
  connection: local
