---

- name: First logon
  shell: |
    {{ role_path }}/scripts/first.logon.sh "{{ args_first_ipaddress }}" "{{ args_first_admin_password }}" "{{ args_first_expect }}" "{{ args_first_install_username }}" "{{ args_first_install_password }}"
    if [[ "$?" != "0" ]]; then
      echo "Error executing script" 
    fi
  args:
    executable: /bin/bash
  register: expectresult
  changed_when: '"Changed" in expectresult.stdout'
  failed_when: '("Error" in expectresult.stdout) or ("Host key verification failed." in expectresult.stdout)'
  connection: local
  become: false
