---

- name: Ensure autologon
  shell: ../scripts/auto.logon.sh "{{ args_ipaddress }}" "{{ args_admin_username }}" "{{ args_admin_password }}" "{{ args_local_user_ssh_key }}" "{{ args_local_user_ssh_pub }}" "{{ args_autologon_expect }}"
  args:
    executable: /bin/bash
  register: expectresult
  changed_when: '"Changed" in expectresult.stdout'
  failed_when: '"Error" in expectresult.stdout'
  connection: local
  become: false
