---

- name: "Playbook: Build Template"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role: # buildostemplate
        name: alex.preinstall.buildostemplate
