---

- name: "Playbook: Build Template"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role:
        name: alex.preinstall.newtemplateinitializebase
      vars:
        args_newtemplateinitialize_host: "{{ prop_proxmox_host }}"
        args_newtemplateinitialize_local_user_ssh: "{{ prop_local_user_ssh }}"
        args_newtemplateinitialize_vmid: "{{ prop_proxmox_vmid }}"
        args_newtemplateinitialize_templateid: "{{ prop_proxmox_template }}"
        args_newtemplateinitialize_name: "{{ prop_proxmox_name }}"
        args_newtemplateinitialize_hostname: "{{ prop_hostname }}"
        args_newtemplateinitialize_description: "{{ prop_description }}"
        args_newtemplateinitialize_ipaddress: "{{ prop_ipaddress }}"
        args_newtemplateinitialize_mac: "{{ prop_vm_mac }}"
        args_newtemplateinitialize_vlan: "{{ prop_vm_vlan }}"
        args_newtemplateinitialize_mac2: "{{ prop_vm_mac2 | default('0') }}"
        args_newtemplateinitialize_vlan2: "{{ prop_vm_vlan2 | default('0')}}"
        args_newtemplateinitialize_memory: "{{ prop_vm_memory }}"
        args_newtemplateinitialize_cores: "{{ prop_vm_cores }}"
        args_newtemplateinitialize_start_boot: "{{ prop_vm_start_boot }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.firstlogon
      vars:
        args_first_ipaddress: "{{ prop_ipaddress }}"
        args_first_admin_password: "{{ prop_admin_password }}"
        args_first_expect: "{{ prop_firstlogon_expect }}"
        args_first_install_username: "{{ prop_install_username }}"
        args_first_install_password: "{{ prop_install_password }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.knownhost
      vars:
        args_knownhost_ipaddress: "{{ prop_ipaddress }}"
        args_knownhost_local_user_ssh: "{{ prop_local_user_ssh }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.adduser
      vars:
        args_adduser_ipaddress: "{{ prop_ipaddress }}"
        args_adduser_admin_username: "{{ prop_admin_username }}"
        args_adduser_admin_password: "{{ prop_admin_password }}"
        args_adduser_install_username: "{{ prop_install_username }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.autologon
      vars:
        args_autologon_ipaddress: "{{ prop_ipaddress }}"
        args_autologon_admin_username: "{{ prop_admin_username }}"
        args_autologon_admin_password: "{{ prop_admin_password }}"
        args_autologon_ssh_key: "{{ prop_local_user_ssh_key }}"
        args_autologon_ssh_pub: "{{ prop_local_user_ssh_pub }}"
        args_autologon_expect: "{{ prop_autologon_expect }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.sudouser
      vars:
        args_sudouser_ipaddress: "{{ prop_ipaddress }}"
        args_sudouser_admin_username: "{{ prop_admin_username }}"
        args_sudouser_admin_password: "{{ prop_admin_password }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.remoteinstallpython3
      vars:
        args_python3_ipaddress: "{{ prop_ipaddress }}"
        args_python3_admin_username: "{{ prop_admin_username }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.certificates
      vars:
        args_cert_ipaddress: "{{ prop_ipaddress }}"
        args_cert_admin_username: "{{ prop_admin_username }}"
        args_cert_admin_groupname: "{{ prop_admin_groupname }}"
        args_cert_basename: "{{ prop_basename }}"
        args_cert_certificates_ca: "{{ prop_certificates_ca }}"
        args_cert_description: "{{ prop_description }}"
        args_cert_hostname: "{{ prop_hostname }}"
        args_cert_dns_local: "{{ prop_dns_local }}"
        args_cert_certificates_sources: "{{ prop_certificates_sources }}"
        args_cert_certificates_server_template: "{{ prop_certificates_server_template }}"
        args_cert_certificates_org_settings: "{{ prop_certificates_org_settings }}"

    - ansible.builtin.include_role:
        name: alex.ms.server
      vars:
        args_server_ipaddress: "{{ prop_ipaddress }}"

    - ansible.builtin.include_role:
        name: alex.linux.installsmbclient
      vars:
        args_smbclient_ipaddress: "{{ prop_ipaddress }}"
        args_smbclient_username: "{{ prop_admin_username }}"
        args_smbclient_password: "{{ prop_admin_password }}"
        args_smbclient_groupname: "{{ prop_admin_groupname }}"
        args_smbclient_basename: "{{ prop_basename }}"

    - ansible.builtin.include_role:
        name: alex.linux.mountsmbshare
      vars:
        args_mountsmb_ipaddress: "{{ prop_ipaddress }}"
        args_mountsmb_ipaddress: "{{ prop_ipaddress }}"
        args_mountsmb_mounts: "{{ prop_smb_mounts }}"
        args_mountsmb_username: "{{ prop_admin_username }}"
        args_mountsmb_basename: "{{ prop_basename }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.configuser
      vars:
        args_user_ipaddress: "{{ prop_ipaddress }}"
        args_user_username: "{{ prop_admin_username }}"
        args_user_group: "{{ prop_admin_groupname }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.newtemplatefinalize
      vars:
        args_newtemplatefinalize_hostname: "{{ prop_hostname }}"
        args_newtemplatefinalize_ipaddress: "{{ prop_ipaddress }}"
        args_newtemplatefinalize_vmid: "{{ prop_proxmox_vmid }}"
        args_newtemplatefinalize_host: "{{ prop_proxmox_host }}"
