---

- name: "Playbook: configurelaptop"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role:
        name: alex.preinstall.firstlogon
      vars:
        args_first_ipaddress: "{{ prop_ipaddress }}"
        args_first_admin_password: "{{ prop_admin_password }}"
        args_first_expect: "{{ prop_firstlogon_expect }}"
        args_first_install_username: "{{ prop_install_username }}"
        args_first_install_password: "{{ prop_install_password }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.knownhost
      vars:
        args_knownhost_ipaddress: "{{ prop_ipaddress }}"
        args_knownhost_local_user_ssh: "{{ prop_local_user_ssh }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.adduser
      vars:
        args_adduser_ipaddress: "{{ prop_ipaddress }}"
        args_adduser_admin_username: "{{ prop_admin_username }}"
        args_adduser_admin_password: "{{ prop_admin_password }}"
        args_adduser_install_username: "{{ prop_install_username }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.autologon
      vars:
        args_autologon_ipaddress: "{{ prop_ipaddress }}"
        args_autologon_admin_username: "{{ prop_admin_username }}"
        args_autologon_admin_password: "{{ prop_admin_password }}"
        args_autologon_ssh_key: "{{ prop_local_user_ssh_key }}"
        args_autologon_ssh_pub: "{{ prop_local_user_ssh_pub }}"
        args_autologon_expect: "{{ prop_autologon_expect }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.sudouser
      vars:
        args_sudouser_ipaddress: "{{ prop_ipaddress }}"
        args_sudouser_admin_username: "{{ prop_admin_username }}"
        args_sudouser_admin_password: "{{ prop_admin_password }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.remoteinstallpython3
      vars:
        args_python3_ipaddress: "{{ prop_ipaddress }}"
        args_python3_admin_username: "{{ prop_admin_username }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.certificates
      vars:
        args_cert_ipaddress: "{{ prop_ipaddress }}"
        args_cert_admin_username: "{{ prop_admin_username }}"
        args_cert_admin_groupname: "{{ prop_admin_groupname }}"
        args_cert_basename: "{{ prop_basename }}"
        args_cert_certificates_ca: "{{ prop_certificates_ca }}"
        args_cert_description: "{{ prop_description }}"
        args_cert_hostname: "{{ prop_hostname }}"
        args_cert_dns_local: "{{ prop_dns_local }}"
        args_cert_certificates_sources: "{{ prop_certificates_sources }}"
        args_cert_certificates_server_template: "{{ prop_certificates_server_template }}"
        args_cert_certificates_org_settings: "{{ prop_certificates_org_settings }}"

    - ansible.builtin.include_role:
        name: alex.linux.installsmbclient
      vars:
        args_smbclient_ipaddress: "{{ prop_ipaddress }}"
        args_smbclient_username: "{{ prop_admin_username }}"
        args_smbclient_password: "{{ prop_admin_password }}"
        args_smbclient_groupname: "{{ prop_admin_groupname }}"
        args_smbclient_basename: "{{ prop_basename }}"

    - ansible.builtin.include_role:
        name: alex.linux.mountsmbshare
      vars:
        args_mountsmb_ipaddress: "{{ prop_ipaddress }}"
        args_mountsmb_ipaddress: "{{ prop_ipaddress }}"
        args_mountsmb_mounts: "{{ prop_smb_mounts }}"
        args_mountsmb_username: "{{ prop_admin_username }}"
        args_mountsmb_basename: "{{ prop_basename }}"

    - ansible.builtin.include_role:
        name: alex.ms.server
      vars:
        args_server_ipaddress: "{{ prop_ipaddress }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.hostname
      vars:
        args_hostname_hostname: "{{ prop_hostname }}"
        args_hostname_ipaddress: "{{ prop_ipaddress }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.configuser
      vars:
        args_user_ipaddress: "{{ prop_ipaddress }}"
        args_user_username: "{{ prop_admin_username }}"
        args_user_group: "{{ prop_admin_groupname }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.aptupgrade
      vars:
        args_apt_ipaddress: "{{ prop_ipaddress }}"
