---

- name: "Playbook: Preinstall on proxmox hosted vm"
  hosts: "{{ args_host }}"
  gather_facts: false
  become: true
  vars:
    ansible_host: "{{ prop_ipaddress }}"

  vars_files:
    - /etc/ansible/inventory/vars.yml

  roles:
    - name: alex.preinstall.waitstarted
    - name: alex.preinstall.knownhost
      vars:
        args_ipaddress: "{{ prop_ipaddress }}"
    - name: alex.preinstall.firstlogon
    - name: alex.preinstall.adduser
    - name: alex.preinstall.autologon
    - name: alex.preinstall.sudouser
    - name: alex.preinstall.remoteinstallpython3
    - name: alex.preinstall.certificates
    - name: alex.preinstall.hostname
    - name: alex.preinstall.aptupgrade
