---

- name: "Playbook: Build VM"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml


  tasks:
    - ansible.builtin.include_role:
        name: alex.preinstall.knownhost
      vars:
        args_knownhost_ipaddress: "{{ prop_proxmox_host }}"
        args_knownhost_local_user_ssh: "{{ prop_local_user_ssh }}"

    - ansible.builtin.include_role:
        name: alex.proxmox.rebuild
      vars:
        args_rebuild_vmid: "{{ prop_proxmox_vmid }}"
        args_rebuild_host: "{{ prop_proxmox_host }}"
        args_rebuild_templateid: "{{ prop_proxmox_template }}"
        args_rebuild_name: "{{ prop_proxmox_name }}"
        args_rebuild_hostname: "{{ prop_hostname }}"
        args_rebuild_description: "{{ prop_description }}"
        args_rebuild_ipaddress: "{{ prop_ipaddress }}"
        args_rebuild_mac: "{{ prop_vm_mac }}"
        args_rebuild_vlan: "{{ prop_vm_vlan }}"
        args_rebuild_mac2: "{{ prop_vm_mac2 | default('0') }}"
        args_rebuild_vlan2: "{{ prop_vm_vlan2 | default('0')}}"
        args_rebuild_memory: "{{ prop_vm_memory }}"
        args_rebuild_cores: "{{ prop_vm_cores }}"
        args_rebuild_start_boot: "{{ prop_vm_start_boot }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.waitstarted
      vars:
        args_rebuild_ipaddress: "{{ prop_ipaddress }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.knownhost
      vars:
        args_knownhost_ipaddress: "{{ prop_ipaddress }}"
        args_knownhost_local_user_ssh: "{{ prop_local_user_ssh }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.resetsshhostcert
      vars:
        args_reset_ipaddress: "{{ prop_ipaddress }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.knownhost
      vars:
        args_knownhost_ipaddress: "{{ prop_ipaddress }}"
        args_knownhost_local_user_ssh: "{{ prop_local_user_ssh }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.hostname
      vars:
        args_hostname_hostname: "{{ prop_hostname }}"
        args_hostname_ipaddress: "{{ prop_ipaddress }}"

    - ansible.builtin.include_role:
        name: alex.preinstall.aptupgrade
      vars:
        args_apt_ipaddress: "{{ prop_ipaddress }}"


